# Generated by Django 3.1.2 on 2020-10-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.BigIntegerField(primary_key=True, serialize=False)),
                ('detalle_ciudad', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.BigIntegerField(primary_key=True, serialize=False)),
                ('detalle_pais', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_tipo_usuario', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_cliente', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.BigIntegerField()),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
