# Generated by Django 3.1.2 on 2020-11-01 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('apellido', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.BigIntegerField()),
                ('email', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateField(blank=True, null=True)),
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('is_staff', models.FloatField(blank=True, default=0, null=True)),
                ('is_active', models.FloatField(blank=True, default=1, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.FloatField(blank=True, default=0, null=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BrProductosProcesoDeVenta',
            fields=[
                ('id_productos_proceso', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'br_productos_proceso_de_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BrUsuariosProcesoDeVenta',
            fields=[
                ('id_br_usuarios_proceso', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'br_usuarios_proceso_de_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalidadProducto',
            fields=[
                ('id_calidad', models.AutoField(primary_key=True, serialize=False)),
                ('detalle_calidad', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'calidad_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.IntegerField(primary_key=True, serialize=False)),
                ('detalle_comuna', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('detalle_contrato', models.CharField(max_length=150)),
                ('fecha_inicio', models.CharField(max_length=20)),
                ('fecha_actualizacion', models.CharField(max_length=20)),
                ('fecha_termino', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_dventa', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_dventa', models.CharField(max_length=150)),
                ('iva', models.DecimalField(decimal_places=1, max_digits=2)),
                ('monto', models.BigIntegerField()),
                ('monto_total', models.BigIntegerField()),
                ('cuotas', models.BigIntegerField()),
                ('monto_envio', models.BigIntegerField(blank=True, null=True)),
                ('monto_aduana', models.BigIntegerField(blank=True, null=True)),
                ('pago_servicios', models.BigIntegerField(blank=True, null=True)),
                ('comision_empresa', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalle_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoProducto',
            fields=[
                ('id_estado', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion_estado', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'estado_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormatoProducto',
            fields=[
                ('id_formato', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_formato', models.CharField(max_length=150)),
                ('descripcion_formato', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'formato_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
                ('cantidad', models.BigIntegerField()),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id_moneda', models.BigIntegerField(primary_key=True, serialize=False)),
                ('detalle_moneda', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'moneda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('detalle_pais', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcesoVenta',
            fields=[
                ('id_pventa', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_venta', models.CharField(max_length=100)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('unidades_vendidas', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'proceso_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.IntegerField(primary_key=True, serialize=False)),
                ('detalle_provincia', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'provincia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.BigIntegerField(primary_key=True, serialize=False)),
                ('detalle_region', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id_seguro', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cobrado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'seguro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('id_subasta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('plazo', models.DateField()),
                ('solicitud_ganadora', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subasta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_usuario', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id_transporte', models.AutoField(primary_key=True, serialize=False)),
                ('tamanio', models.CharField(choices=[('Grande', 'Grande'), ('Mediano', 'Mediano'), ('Pequeño', 'Pequeño')], max_length=20)),
                ('capacidad_carga', models.CharField(max_length=150)),
                ('refrigeracion', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
            ],
            options={
                'db_table': 'transporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=150)),
                ('precio_unitario', models.IntegerField(db_column='precio_unitario')),
                ('imagen', models.ImageField(blank=True, upload_to='productos/')),
                ('id_calidad', models.ForeignKey(db_column='id_calidad', on_delete=django.db.models.deletion.DO_NOTHING, to='registration.calidadproducto')),
                ('id_estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.DO_NOTHING, to='registration.estadoproducto')),
                ('id_formato', models.ForeignKey(db_column='id_formato', on_delete=django.db.models.deletion.DO_NOTHING, to='registration.formatoproducto')),
                ('id_inventario', models.ForeignKey(blank=True, db_column='id_inventario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='registration.inventario')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['id_producto'],
            },
        ),
    ]
