# Generated by Django 3.1.1 on 2020-10-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id_transporte', models.AutoField(primary_key=True, serialize=False)),
                ('tamanio', models.CharField(choices=[('Grande', 'Grande'), ('Mediano', 'Mediano'), ('Pequeño', 'Pequeño')], max_length=20)),
                ('capacidad_carga', models.CharField(max_length=150)),
                ('refrigeracion', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
            ],
            options={
                'db_table': 'transporte',
                'managed': False,
            },
        ),
    ]
